### PR TITLE
Add a Prometheus node as an optional part of the setup

### PR DESCRIPTION
**Pull request by mmagician**
+ configures the metrics collection ports to only allow access from the prometheus node (added security), if prometheus is enabled

### CODE REVIEW

**Comment by lamafab** [comment]
Thanks! Only went over it briefly, but looks fine for now. You might want to adjust that README. Also, what's up with that `nginx.conf`? :thinking:

**Comment by mmagician** [comment]
@lamafab The latest updates should take care of that. Thanks for pointing it out

**Comment by lamafab** [comment]
@mmagician agreed to add basic HTTP authentication to the Prometheus interface on port `9090`.

**Comment by mmagician** [comment]
@lamafab nginx listens at `localhost:9091/prometheus`, with basic auth and does a proxy-pass to the prometheus service running on 9090.

**Comment by lamafab** [comment]
As discussed directly, this should be in a separate repo. Let's follow the KISS approach for this repository.

**Pull request closed without merging**
